<template>
    <div class="container mx-auto mr-4">
      <SearchBar @keyword="setKeyword" />
      <div class="grid grid-cols-3 gap-4" v-if="!isLoading">
        <ImageGrid :imageList="keyword.length > 0 ? getSearchedImages : getAllImages" v-if="getAllImages || getSearchedImages" />
      </div>
      <div v-else class="loadingio-spinner-spinner-gr914qevmqg object-none object-center"><div class="ldio-4mrldkxj9zx">
      <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
      </div></div>
      <ul class="space-x-4 ml-96">
        <li v-for="i in pageCount" :key="i" class="inline">
          <a
            class="
              cursor-pointer
              hover:text-red-500
              hover:underline
              text-blue-600
              visited:text-purple-600
            "
            @click="perPageData(i-1)"
            >{{ i }}</a
          >
        </li>
      </ul>
    </div>
</template>

<script>
// @ is an alias to /src
import SearchBar from "../../components/SearchBar.vue"
import ImageGrid from "../../components/ImageGrid.vue";
import {mapActions, mapGetters} from "vuex"
export default {
  name: "Home",
  components: {
    ImageGrid,
    SearchBar,
  },
  data() {
    return {
      keyword: "",
      pageCount: 10,
      currentPage: 0,
      isLoading: true
    };
  },
  mounted() {
    this.perPageData(1)
  },
  computed: {
    ...mapGetters(["getAllImages", "getSearchedImages"])
  },
  methods: {
    ...mapActions(["fetchAllImages", "fetchSearchImages"]),

    perPageData(i) {
      this.currentPage = i ;
      if(this.keyword.length > 0){
        this.fetchSearchImages({keyword: this.keyword, index: this.currentPage})
      } else {
        this.fetchAllImages(i).then(()=>{
        this.isLoading = false
      })
      }
    },
    setKeyword(keyword) {
      this.keyword = keyword
      this.fetchSearchImages({keyword: keyword,index: this.currentPage})
    }
  },
};
</script>
<style scoped>
@keyframes ldio-4mrldkxj9zx {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-4mrldkxj9zx div {
  left: 94px;
  top: 48px;
  position: absolute;
  animation: ldio-4mrldkxj9zx linear 1s infinite;
  background: #fe718d;
  width: 12px;
  height: 24px;
  border-radius: 6px / 12px;
  transform-origin: 6px 52px;
}.ldio-4mrldkxj9zx div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #fe718d;
}.ldio-4mrldkxj9zx div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #fe718d;
}
.loadingio-spinner-spinner-gr914qevmqg {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-4mrldkxj9zx {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-4mrldkxj9zx div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
